# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stems.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stems.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstems.proto\x12\tvdj.stems\"\x07\n\x05\x45mpty\"W\n\nServerInfo\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x15\n\rgpu_memory_mb\x18\x03 \x01(\x05\x12\r\n\x05ready\x18\x04 \x01(\x08\"\x1b\n\x0bTensorShape\x12\x0c\n\x04\x64ims\x18\x01 \x03(\x03\"L\n\x06Tensor\x12%\n\x05shape\x18\x01 \x01(\x0b\x32\x16.vdj.stems.TensorShape\x12\r\n\x05\x64type\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"t\n\x10InferenceRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x04\x12\x13\n\x0binput_names\x18\x02 \x03(\t\x12!\n\x06inputs\x18\x03 \x03(\x0b\x32\x11.vdj.stems.Tensor\x12\x14\n\x0coutput_names\x18\x04 \x03(\t\"r\n\x11InferenceResponse\x12\x12\n\nsession_id\x18\x01 \x01(\x04\x12\x0e\n\x06status\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\"\n\x07outputs\x18\x04 \x03(\x0b\x32\x11.vdj.stems.Tensor\"p\n\nAudioChunk\x12\x12\n\nsession_id\x18\x01 \x01(\x04\x12\x13\n\x0b\x63hunk_index\x18\x02 \x01(\x03\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x04 \x01(\x05\x12\x12\n\naudio_data\x18\x05 \x01(\x0c\"[\n\tStemChunk\x12\x12\n\nsession_id\x18\x01 \x01(\x04\x12\x13\n\x0b\x63hunk_index\x18\x02 \x01(\x03\x12\x11\n\tstem_name\x18\x03 \x01(\t\x12\x12\n\naudio_data\x18\x04 \x01(\x0c\x32\xd9\x01\n\x0eStemsInference\x12I\n\x0cRunInference\x12\x1b.vdj.stems.InferenceRequest\x1a\x1c.vdj.stems.InferenceResponse\x12\x42\n\x0fStreamInference\x12\x15.vdj.stems.AudioChunk\x1a\x14.vdj.stems.StemChunk(\x01\x30\x01\x12\x38\n\rGetServerInfo\x12\x10.vdj.stems.Empty\x1a\x15.vdj.stems.ServerInfoB\x03\xf8\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stems_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001'
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_SERVERINFO']._serialized_start=35
  _globals['_SERVERINFO']._serialized_end=122
  _globals['_TENSORSHAPE']._serialized_start=124
  _globals['_TENSORSHAPE']._serialized_end=151
  _globals['_TENSOR']._serialized_start=153
  _globals['_TENSOR']._serialized_end=229
  _globals['_INFERENCEREQUEST']._serialized_start=231
  _globals['_INFERENCEREQUEST']._serialized_end=347
  _globals['_INFERENCERESPONSE']._serialized_start=349
  _globals['_INFERENCERESPONSE']._serialized_end=463
  _globals['_AUDIOCHUNK']._serialized_start=465
  _globals['_AUDIOCHUNK']._serialized_end=577
  _globals['_STEMCHUNK']._serialized_start=579
  _globals['_STEMCHUNK']._serialized_end=670
  _globals['_STEMSINFERENCE']._serialized_start=673
  _globals['_STEMSINFERENCE']._serialized_end=890
# @@protoc_insertion_point(module_scope)
